import Head from "next/head";
import { useEffect, useState } from "react";
import { clsx } from "clsx";
import { useRouter } from "next/router";
import Case from "case";

export default function Home() {
  const router = useRouter();
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [formIsInvalid, setFormIsInvalid] = useState(true);

  useEffect(() => {
    setFormIsInvalid(
      !title || !description || title.length > 100 || description.length > 1000
    );
  }, [title, description]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-center">AI Thumbnail Generator</h1>

      <form
        className="w-[400px] mx-auto mb-4"
        method="POST"
        action="/api/create"
        onSubmit={async (event) => {
          event.preventDefault();
          if (!formIsInvalid) {
            // send request to backend
            const response = await fetch("/api/image/create", {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
              },
              body: JSON.stringify({
                title,
                description,
              }),
            });

            const { image } = await response.json();

            console.log({ image });

            if (image) {
              router.push(`/images/${image.id}`);
            }
          }
        }}
      >
        <div className="form-control w-full">
          <label className="label">
            <span className="label-text">What is the title of the video?</span>
          </label>
          <input
            type="text"
            value={title}
            placeholder="Type here"
            className="input input-bordered w-full"
            onInput={(event) => {
              setTitle(event.currentTarget.value);
            }}
          />
        </div>
        <div className="form-control mb-4">
          <label className="label">
            <span className="label-text">
              Description of contents in desired thumbnail
            </span>

            <span className="label-text-alt">
              <span
                className={clsx(
                  {
                    "text-red": description.length > 1000,
                  },
                  "mr-2"
                )}
              >
                {description.length}
              </span>
              / 1000
            </span>
          </label>
          <textarea
            value={description}
            className="textarea textarea-bordered h-24"
            placeholder="Bio"
            onInput={(event) => {
              setDescription(event.currentTarget.value);
            }}
          ></textarea>
        </div>

        <button className="btn btn-primary w-full" disabled={formIsInvalid}>
          Submit
        </button>
      </form>
    </>
  );
}
