import Head from "next/head";

export default function ServerError() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-center">Server Error</h1>

      <p className="text-center">Something has gone terribly wrong.</p>
    </>
  );
}
